### PR TITLE
Fix stopVideo not working for youtube iframe videos

### PR DESCRIPTION
**Pull request by diegoversiani**
Fixed an issue where a youtube video in a modal would still be paying on the background after you close the modal.

It happened because the video was set to autoplay and when the iframe src gets replaced the video reloads and start playing again.

The solution was to replace `autoplay=1` with `autoplay=0` when reseting the iframe src.

### CODE REVIEW

**Comment by diegoversiani** [comment]
@cferdinandi I noticed the build fails on my computer as well because I don't have `jshint` installed globally and the package is not listed on package.json nor installed as a dependency.

**Comment by cferdinandi** [comment]
Yea, the package is a hot mess in need a total rewrite. Sorry about that.

Unfortunately GitHub is showing the entire file as diffed, so I'm not really sure what's been changed here. Can you help?

**Comment by diegoversiani** [comment]
I guess the diff thing is because of hard tabs vs space tabbing, I read the contributing guide and used hard tabs as required there.

The difference is only this:

src/js/modals.js - line 165
**before**
`var iframeSrc = iframe.src;`
**after**
`var iframeSrc = iframe.src.replace( 'autoplay=1', 'autoplay=0' ) ;`

**Comment by cferdinandi** [comment]
Ah yea, I see it now!

So, to be honest, this script is a complete mess and has some serious accessibility issues. I would recommend [using this one from Scott O'Hara instead](https://github.com/scottaohara/accessible_modal_window). It's much better done.

**Comment by diegoversiani** [comment]
Ah I see, that one from Scott seems nice, I'll consider testing and replacing on my current project. Thank you :)

**Pull request closed without merging**
