### PR TITLE
Update modals.js

### PR DESCRIPTION
**Pull request by ryanscherler**
Updated file with correct tab spacing to better show only specific file changes.

### CODE REVIEW

**Comment by ryanscherler** [comment]
How's the updates looking? Any suggestions on what I added?

**Comment by cferdinandi** [comment]
@ryanscherler Sorry man, this looks really good. I do have a few questions/thoughts I'd love your feedback on:

1. Should the class actually go on the `html` element? I can see a situation where someone has `overflow-y` forced on the `html` element, too, and would want to override it (I'm thinking folks who use CSS resets instead of a normalizer). The answer may be, "That's a weird edge case," which is totally fair.
2. Should we include styling to prevent `body` scrolling when the modal is open. As in, not just provide the class, but actually add some lightweight CSS:

        ```css
        body.modal-active {
	    overflow-y: hidden;
            position: relative;
        }
	```
3. In Bootstrap, I believe there's also a bit of JS that adds some `padding-right` value to the body equivalent to the scrollbar width to prevent content-shifting when `overflow-y` is removed. Any thoughts on adding that functionality?
4. What happens if you run `classList.remove` and the class doesn't exist? Does it throw an error or just move on? If no error is thrown, I wonder if we should remove the `classList.contains` check for the new `body` class.

Really appreciate your work here. Once we get this all squared away, I'll update the version number, run a build so this compiles to `dist`, and push some release notes.

**Comment by cferdinandi** [comment]
@ryanscherler Any thoughts?

**Comment by ryanscherler** [comment]
Hey Chris,


Sorry for the delay on your feedback, its been a crazy one here in Washington state with the wildfires and  work / code was on hold for a while. As for the feedback:

1. I also agree the formatting / class should be added to the HTML element, I was actually thinking of that shortly after I made the changes and realized that some folks would likely have overflow properties set on the HTML tag that could override the body class.

2. I am not so sure on styling in the code, I would maybe just keep it to using a CSS class and have the user apply the proper styles in the modal CSS?

3. Some padding right on the body for preventing the jump is likely a good idea - I too have seen that before and seems like a solid plan (would this too be something that would be added in the modal stylesheet or dynamically in the script?)

4. I am not sure on the classList.remove when its not removed (I was just following existing conventions with the code and figured it worth checking before removing) - this is likely not necessary though I honestly don't write a lot of core JS (I am more and more now and realizing all the small things that jQuery used to do without my knowledge).

**Comment by cferdinandi** [comment]
Wow, didn't realize you were out that way. Hope you and your loved ones are all safe! Thoughts/responses:

1. *I also agree the formatting / class should be added to the HTML element, I was actually thinking of that shortly after I made the changes and realized that some folks would likely have overflow properties set on the HTML tag that could override the body class.* I can make this update when I branch your PR and run the build.
2. *I am not so sure on styling in the code, I would maybe just keep it to using a CSS class and have the user apply the proper styles in the modal CSS?* I wouldn't load it with JS, either. I was thinking of adding some light styling to the CSS file to lock the body in place.
3. *Some padding right on the body for preventing the jump is likely a good idea - I too have seen that before and seems like a solid plan (would this too be something that would be added in the modal stylesheet or dynamically in the script?)* This would get applied inline to the body via the JS, but would require me to do some calculations that aren't baked in yet. I'll research this one.
4. *I am not sure on the classList.remove when its not removed (I was just following existing conventions with the code and figured it worth checking before removing) - this is likely not necessary though I honestly don't write a lot of core JS (I am more and more now and realizing all the small things that jQuery used to do without my knowledge).* No worries. I'm not sure either. I'll do a test and see what happens.

**Comment by cferdinandi** [comment]
I had to add this functionality for a client project this week, so I ended up bolting it in to the existing dev branch instead of this fork.

1. Controlled via an option at init (off by default).
2. Provides the ability to add `overflow-y: hidden` to the `<html>` element, the `<body>` element, or both (the default). 
3. Adds `padding-right` equal to the width of the scrollbar so that content does not jump.

See: https://github.com/cferdinandi/modals/pull/40

**Pull request closed without merging**
