### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bvdputte**
npm install info is not correct (running it caused my terminal to "hang")

### CODE REVIEW

**Comment by cferdinandi** [comment]
These updates aren’t correct either. This isn’t a maintained package on NPM. That’s an “install from GitHub” command in the readme.

**Comment by bvdputte** [comment]
I'm sorry, I'm new to all of this.

Does this mean that what I did ("npm install modal.js") isn't the good way to install this package via npm? If not, could you please elaborate on what is?

----

"npm install cferdinandi/modals" causes my terminal to hang. And searching for "cferdinandi/modals" on npm yields no results: https://www.npmjs.com/search?q=cferdinandi%2Fmodals

Thx!

**Comment by cferdinandi** [comment]
You can install with NPM, or, you're supposed to be able to, *from* GitHub.

This pacakge is not published on NPM, but NPM supports (or used to) installed from a GitHub repo. Not sure if it still does, and not sure why it's hanging your system.

Honestly, this plugin has a lot of accessibility issues. You should use this one from @scottohara instead: https://github.com/scottaohara/accessible_modal_window

I need to deprecate this one.

**Comment by cferdinandi** [comment]
Oh, and no need to apologize at all! 😄

**Comment by bvdputte** [comment]
Hmm, I just tried `npm install cferdinandi/modals` again, but at my home WiFi now, and it works... Might have been network-related? Dunno.

Thx for the headsup about accessible modal window plugin. I'll have a look at it tomorrow.

Thx a lot! 😊

**Comment by cferdinandi** [comment]
Modern development is a fickle beast! Good luck, and you're welcome!

**Pull request closed without merging**
